### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by davelab6** [googlefonts/roboto-serif#4]
@m4rc1e I was trying to rebuild with statics...

Perhaps you could (ask Aaron to) move this to the UFR template?

```
$ sh build.sh         
INFO:fontmake.font_project:Building variable font ../fonts/variable/RobotoSerif-VF.ttf
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 1, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 0, 'ItemName:', 'PairSet', 'ItemIndex:', 0)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 0, 'ItemName:', 'PairSet', 'ItemIndex:', 0)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 1, 'ItemName:', 'PairSet', 'ItemIndex:', 10)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 1, 'ItemName:', 'PairSet', 'ItemIndex:', 10)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 1, 'ItemName:', 'PairSet', 'ItemIndex:', 2)
INFO:GFBuilder:Creating variable fonts from RobotoSerif-Italic.designspace
INFO:fontmake.font_project:Building variable font ../fonts/variable/RobotoSerif-Italic-VF.ttf
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 1, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 0, 'ItemName:', 'PairSet', 'ItemIndex:', 2)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 0, 'ItemName:', 'PairSet', 'ItemIndex:', 2)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 0, 'ItemName:', 'PairSet', 'ItemIndex:', 328)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 2, 'ItemName:', 'PairSet', 'ItemIndex:', 0)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 2, 'ItemName:', 'PairSet', 'ItemIndex:', 0)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 2, 'ItemName:', 'PairSet', 'ItemIndex:', 0)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 2, 'ItemName:', 'PairSet', 'ItemIndex:', 81)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 5, 'ItemName:', 'PairSet', 'ItemIndex:', 123)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 5, 'ItemName:', 'PairSet', 'ItemIndex:', 123)
INFO:GFBuilder:Postprocessing font ../fonts/variable/RobotoSerif[GRAD,opsz,wdth,wght].ttf
WARNING:gftools.fix:Cannot remove tables '['MVAR']' since they are not in the font.
INFO:GFBuilder:Postprocessing font ../fonts/variable/RobotoSerif-Italic[GRAD,opsz,wdth,wght].ttf
INFO:gftools.fix:Removing tables '['MVAR']' from font
INFO:GFBuilder:Creating static fonts from RobotoSerif.designspace
INFO:fontmake.font_project:Interpolating master UFOs from designspace
WARNING:fontmake.instantiator:The source temp_master.0 (Roboto_Serif_Text-Super_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.1 (Roboto_Serif_Text-Super_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.2 (Roboto_Serif_Text-Super.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.4 (Roboto_Serif_Text-Regular_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.6 (Roboto_Serif_Text-Hairline_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.7 (Roboto_Serif_Text-Hairline_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.8 (Roboto_Serif_Text-Hairline.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.9 (Roboto_Serif_Text_Wide-Super.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.10 (Roboto_Serif_Text_Wide-Regular.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.11 (Roboto_Serif_Text_Wide-Hairline.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.12 (Roboto_Serif_Text_Wide-Super_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.13 (Roboto_Serif_Text_Wide-Super_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.16 (Roboto_Serif_Text_Wide-Hairline_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.17 (Roboto_Serif_Text_Wide-Hairline_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.18 (Roboto_Serif_Text_Cond-Super.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.20 (Roboto_Serif_Text_Cond-Hairline.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.21 (Roboto_Serif_Text_Cond-Super_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.22 (Roboto_Serif_Text_Cond-Super_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.25 (Roboto_Serif_Text_Cond-Hairline_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.26 (Roboto_Serif_Text_Cond-Hairline_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.27 (Roboto_Serif_Micro-Super.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.28 (Roboto_Serif_Micro-Regular.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.29 (Roboto_Serif_Micro-Hairline.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.30 (Roboto_Serif_Micro_Wide-Super.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.31 (Roboto_Serif_Micro_Wide-Regular.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.32 (Roboto_Serif_Micro_Wide-Hairline.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.33 (Roboto_Serif_Micro_Cond-Super.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.34 (Roboto_Serif_Micro_Cond-Regular.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.35 (Roboto_Serif_Micro_Cond-Hairline.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.36 (Roboto_Serif_Display-Super.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.37 (Roboto_Serif_Display-Regular.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.38 (Roboto_Serif_Display-Hairline.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.39 (Roboto_Serif_Display_Wide-Super.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.40 (Roboto_Serif_Display_Wide-Regular.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.41 (Roboto_Serif_Display_Wide-Hairline.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.42 (Roboto_Serif_Display_Cond-Super.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.43 (Roboto_Serif_Display_Cond-Regular.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.44 (Roboto_Serif_Display_Cond-Hairline.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.45 (Roboto_Serif_Display_Cond-Super_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.46 (Roboto_Serif_Display_Cond-Super_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.47 (Roboto_Serif_Display_Cond-Regular_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.48 (Roboto_Serif_Display_Cond-Regular_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.49 (Roboto_Serif_Display_Cond-Hairline_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.50 (Roboto_Serif_Display_Cond-Hairline_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.51 (Roboto_Serif_Display_Wide-Super_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.52 (Roboto_Serif_Display_Wide-Super_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.53 (Roboto_Serif_Display_Wide-Regular_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.54 (Roboto_Serif_Display_Wide-Regular_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.55 (Roboto_Serif_Display_Wide-Hairline_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.56 (Roboto_Serif_Display_Wide-Hairline_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.57 (Roboto_Serif_Micro_Cond-Super_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.58 (Roboto_Serif_Micro_Cond-Super_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.61 (Roboto_Serif_Micro_Cond-Hairline_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.62 (Roboto_Serif_Micro_Cond-Hairline_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.63 (Roboto_Serif_Micro_Wide-Super_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.64 (Roboto_Serif_Micro_Wide-Super_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.65 (Roboto_Serif_Micro_Wide-Regular_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.66 (Roboto_Serif_Micro_Wide-Regular_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.67 (Roboto_Serif_Micro_Wide-Hairline_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.68 (Roboto_Serif_Micro_Wide-Hairline_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.75 (Roboto_Serif_Display-Super_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.76 (Roboto_Serif_Display-Super_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.77 (Roboto_Serif_Display-Regular_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.78 (Roboto_Serif_Display-Regular_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.79 (Roboto_Serif_Display-Hairline_G4.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.80 (Roboto_Serif_Display-Hairline_G1.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
INFO:fontmake.font_project:Generating instance UFO for "None"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fontmake/font_project.py", line 946, in run_from_designspace
    self._run_from_designspace_static(
  File "/usr/local/lib/python3.9/site-packages/fontmake/font_project.py", line 1006, in _run_from_designspace_static
    ufos.extend(
  File "/usr/local/lib/python3.9/site-packages/fontmake/font_project.py", line 792, in interpolate_instance_ufos
    raise ValueError(
ValueError: It is currently required that instances have filenames set.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/gftools-builder.py", line 83, in <module>
    builder.build()
  File "/usr/local/lib/python3.9/site-packages/gftools/builder/__init__.py", line 180, in build
    self.build_static()
  File "/usr/local/lib/python3.9/site-packages/gftools/builder/__init__.py", line 386, in build_static
    self.build_a_static_format("otf", self.config["otDir"], self.post_process)
  File "/usr/local/lib/python3.9/site-packages/gftools/builder/__init__.py", line 443, in build_a_static_format
    for fontfile in self.run_fontmake(source, args):
  File "/usr/local/lib/python3.9/site-packages/gftools/builder/__init__.py", line 317, in run_fontmake
    FontProject().run_from_designspace(source, **args)
  File "/usr/local/lib/python3.9/site-packages/fontmake/font_project.py", line 974, in run_from_designspace
    raise FontmakeError(
fontmake.errors.FontmakeError: In 'RobotoSerif.designspace': Generating fonts from Designspace failed: It is currently required that instances have filenames set.
  File "fix_names.py", line 15
    roman_name.setName(f"{version};COMM;RobotoSerif-20ptRegular", 3, 3, 1, 0x409)
                                                               ^
SyntaxError: invalid syntax
$
```

**Comment by m4rc1e** [comment]
It appears you're using a version of Python which doesn't support formatted string literals, https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals.

Gftools now requires versions of Python which do support this (it won't install otherwise) so I'm going to close this.
